---
spring:
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:todos
    driver-class-name: org.h2.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
logging:
  level:
    com.redhat.consultant360: INFO
    org.hibernate.SQL: ERROR

management:
  endpoint:
    health:
      group:
        readiness:
          include: db
        liveness:
          include: ping